image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.5.0

stages:
- maven-package
- docker-build
- sonar_check

package:
  stage: maven-package
  script:
  - maven_install
  - cache_jar
  only:
  - develop
  - /^hotfix-.*$/
  - /^release-.*$/
  - tags

#sonar_check:
#  stage: sonar_check
#  script:
#  - sonar_check
#  only:
#  - develop

docker_build:
  stage: docker-build
  script:
  - docker_build
  - clean_cache
  - chart_build
  only:
  - develop
  - /^release-.*$/
  - /^hotfix-.*$/
  - tags

.auto_devops: &auto_devops |
  curl -o .auto_devops.sh \
      "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"
  if [ $? -ne 0 ];then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

  function maven_install() {
    mvn clean install -Dgpg.skip -Dmaven.test.skip=true -U
  }


  function cache_jar(){
    mkdir -p /cache/$CI_PROJECT_NAME-$CI_PROJECT_ID-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA/
    cp -rf target/app.jar /cache/$CI_PROJECT_NAME-$CI_PROJECT_ID-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA/
  }

  function docker_build() {
    cp -r /cache/$CI_PROJECT_NAME-$CI_PROJECT_ID-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA/app.jar docker/
    docker login -u ${DOCKER_USER} -p ${DOCKER_PWD} ${DOCKER_REGISTRY}
    docker build --pull -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} docker
    docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
  }

  function clean_cache(){
    rm -rf /cache/$CI_PROJECT_NAME-$CI_PROJECT_ID-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA
  }

before_script:
- *auto_devops
